# Generated by Django 5.2.1 on 2025-06-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
